# Generated by Django 2.1.4 on 2019-01-22 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyname', models.CharField(max_length=50, verbose_name='小说名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('intro', models.CharField(max_length=1000, verbose_name='简介')),
                ('coverimg', models.CharField(max_length=100, verbose_name='封面图')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '小说表',
                'db_table': 'db_articleinfo',
            },
        ),
        migrations.CreateModel(
            name='SectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='章节名')),
                ('contnets', models.TextField(max_length=30000, verbose_name='内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ArticleInfo')),
            ],
            options={
                'verbose_name_plural': '章节表',
                'db_table': 'db_sectioninfo',
            },
        ),
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类名')),
            ],
            options={
                'verbose_name_plural': '类别表',
                'db_table': 'db_typeinfo',
            },
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.TypeInfo'),
        ),
    ]
