# Generated by Django 2.1.4 on 2019-01-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='istop',
            field=models.BooleanField(default=True),
        ),
    ]
