# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_articleinfo_istop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='istop',
            field=models.BooleanField(default=True, verbose_name='是否推荐'),
        ),
    ]
